stages:
- check
- build

lint:
  stage: check
  image: golang:1.17.9
  script:
  - go fmt .

audit:
  stage: check
  image: golang:1.17.9
  script:
  - go vet .

build:
  stage: build
  image: golang:1.17.9
  script:
  - |
    go build \
        -ldflags "-X main.Version=${CI_COMMIT_REF_NAME} -X main.Author=${AUTHOR}" \
        -o hello \
        .
