stages:
- build

services:
- docker:29.1.5-dind

default:
  image: docker:29.1.5

variables:
  DOCKER_BUILDKIT: 1

.docker-login:
  before_script:
  - docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  after_script:
  - docker logout ${CI_REGISTRY}

build:
  stage: build
  extends: .docker-login
  script:
  - |
    docker build . \
        --cache-from ${CI_REGISTRY_IMAGE}:dev \
        --tag ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID} \
        --tag ${CI_REGISTRY_IMAGE}:dev
  - docker push ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}
  - docker push ${CI_REGISTRY_IMAGE}:dev
