package:
  image: docker:20.10.16
  stage: package

  services:
  - name: docker:20.10.16-dind
    command: [ "dockerd", "--host", "tcp://0.0.0.0:2375" ]

  before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}

  script:
  - docker build --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" .
  - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

