# https://docs.docker.com/compose/compose-file

volumes:
  portainer-data:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  vscode_config:
  vscode_project:

services:

  # https://doc.traefik.io/traefik/
  traefik:
    image: traefik:v2.8
    command:
    - --log=true
    - --log.level=DEBUG
    - --api=true
    - --api.dashboard=true
    - --entrypoints.http.address=:80
    - --entrypoints.https.address=:443
    - --entrypoints.ssh.address=:2222
    - --providers.file.directory=/etc/traefik/conf.d
    - --providers.docker=true
    - --providers.docker.exposedByDefault=false
    ports:
    - 2222:2222
    - 80:80
    - 443:443
    volumes:
    - ./traefik.d:/etc/traefik/conf.d:ro
    - /root/ssl:/etc/traefik/ssl:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "netstat -tunapl | grep LISTEN | grep :80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Global authentication middlewares
      traefik.http.middlewares.seat-auth.basicauth.users: ${SEAT_HTPASSWD:?You must supply SEAT_HTPASSWD}
      traefik.http.middlewares.seat-code.basicauth.users: ${SEAT_CODE_HTPASSWD:?You must supply SEAT_CODE_HTPASSWD}
      # Global redirection middleware
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # traefik dashboard: redirection to HTTPS
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.traefik.middlewares: redirect-to-https
      # traefik dashboard: authenticated endpoint
      traefik.http.routers.traefik-s.entrypoints: https
      traefik.http.routers.traefik-s.service: api@internal
      traefik.http.routers.traefik-s.rule: Host(`traefik.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.traefik-s.tls: "true"
      traefik.http.routers.traefik-s.middlewares: seat-auth

  nginx:
    build:
      context: nginx
    environment:
      SEAT_INDEX: ${SEAT_INDEX:?You must supply SEAT_INDEX}
      SEAT_PASS: ${SEAT_PASS:?You must supply SEAT_PASS}
      SEAT_CODE: ${SEAT_CODE:?You must supply SEAT_CODE}
      DOMAIN: ${DOMAIN:?You must supply DOMAIN}
    labels:
      traefik.enable: "true"
      # Service port
      traefik.http.services.nginx.loadbalancer.server.port: 80
      # Redirection to HTTPS
      traefik.http.routers.nginx.entrypoints: http
      traefik.http.routers.nginx.rule: Host(`${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.nginx.service: nginx
      traefik.http.routers.nginx.middlewares: redirect-to-https
      # Unauthenticated endpoint
      traefik.http.routers.nginx-s.entrypoints: https
      traefik.http.routers.nginx-s.rule: Host(`${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.nginx-s.service: nginx
      traefik.http.routers.nginx-s.tls: "true"
      # Authenticated endpoint
      traefik.http.routers.auth-s.entrypoints: https
      traefik.http.routers.auth-s.rule: Host(`${DOMAIN:?You must supply DOMAIN}`) && PathPrefix(`/auth/`)
      traefik.http.routers.auth-s.service: nginx
      traefik.http.routers.auth-s.tls: "true"
      traefik.http.routers.auth-s.middlewares: seat-code
      # Redirection to HTTPS for dev
      traefik.http.routers.dev.entrypoints: http
      traefik.http.routers.dev.rule: Host(`dev.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.dev.service: nginx
      traefik.http.routers.dev.middlewares: redirect-to-https
      # Authenticated endpoint for dev
      traefik.http.routers.dev-s.entrypoints: https
      traefik.http.routers.dev-s.rule: Host(`dev.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.dev-s.service: nginx
      traefik.http.routers.dev-s.tls: "true"
      # Redirection to HTTPS for live
      traefik.http.routers.live.entrypoints: http
      traefik.http.routers.live.rule: Host(`live.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.live.service: nginx
      traefik.http.routers.live.middlewares: redirect-to-https
      # Authenticated endpoint for live
      traefik.http.routers.live-s.entrypoints: https
      traefik.http.routers.live-s.rule: Host(`live.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.live-s.service: nginx
      traefik.http.routers.live-s.tls: "true"

  portainer:
    image: portainer/portainer-ce:2.13.1-alpine
    command:
    - --admin-password=${SEAT_HTPASSWD_ONLY}
    - --host=unix:///var/run/docker.sock
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer-data:/data
    ports:
    - 9000:9000
    labels:
      traefik.enable: "true"
      # Service port
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      # Redirection to HTTPS
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.portainer.service: portainer
      traefik.http.routers.portainer.middlewares: redirect-to-https
      # Unauthenticated endpoint
      traefik.http.routers.portainer-s.entrypoints: https
      traefik.http.routers.portainer-s.rule: Host(`portainer.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.portainer-s.service: portainer
      traefik.http.routers.portainer-s.tls: "true"

  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: gitlab/gitlab-ce:15.3.4-ce.0
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Berlin'

        gitlab_rails['usage_ping_enabled'] = false

        external_url 'https://gitlab.${DOMAIN:?You must supply DOMAIN}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['real_ip_trusted_addresses'] = [ '172.16.0.0/12' ]
        nginx['real_ip_header'] = 'X-Real-Ip'
        nginx['real_ip_recursive'] = 'on'
        letsencrypt['enable'] = false

        gitlab_pages['enable'] = true
        pages_external_url 'https://gitlab.${DOMAIN:?You must supply DOMAIN}'
        pages_nginx['listen_https'] = false
        # Required due to https://gitlab.com/gitlab-org/gitlab-pages/issues/129
        gitlab_pages['inplace_chroot'] = true
        # Set listen-proxy when behind reverse proxy. see https://docs.gitlab.com/ee/administration/pages/#configure-listener-for-reverse-proxy-requests
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        # Fix for https://gitlab.com/gitlab-org/gitlab-pages/-/issues/534
        gitlab_pages['internal_gitlab_server'] = "http://127.0.0.1"

        registry_external_url 'https://gitlab.${DOMAIN:?You must supply DOMAIN}'
        registry['registry_http_addr'] = "0.0.0.0:5000"
        registry_nginx['listen_https'] = false

        # Prevent conflict with host SSH port
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        grafana['alerting_enabled'] = true
        # Fix for chicken-and-egg issue with oauth
        grafana['disable_login_form'] = false
    # https://docs.gitlab.com/ee/install/docker.html#devshm-mount-not-having-enough-space-in-docker-container
    shm_size: 256m
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_config:/etc/gitlab
    - gitlab_logs:/var/log/gitlab
    - gitlab_data:/var/opt/gitlab
    labels:
      traefik.enable: "true"
      # Web UI: service port
      traefik.http.services.www.loadbalancer.server.port: 80
      # Web UI: redirection to HTTPS
      traefik.http.routers.www.entrypoints: http
      traefik.http.routers.www.rule: Host(`gitlab.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.www.service: www
      traefik.http.routers.www.middlewares: redirect-to-https
      # Web UI: unauthenticated endpoint
      traefik.http.routers.www-s.entrypoints: https
      traefik.http.routers.www-s.rule: Host(`gitlab.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.www-s.service: www
      traefik.http.routers.www-s.tls: "true"
      # Pages: service port
      traefik.http.services.pages.loadbalancer.server.port: 8090
      # Pages: redirection to HTTPS
      traefik.http.routers.pages.entrypoints: http
      traefik.http.routers.pages.middlewares: redirect-to-https
      traefik.http.routers.pages.rule: HostRegexp(`{subdomain:.+}.gitlab.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.pages.service: pages
      # Pages: unauthenticated endpoint
      traefik.http.routers.pages-s.entrypoints: https
      traefik.http.routers.pages-s.rule: HostRegexp(`{subdomain:.+}.gitlab.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.pages-s.service: pages
      traefik.http.routers.pages-s.tls: "true"
      # Registry: service port
      traefik.http.services.registry.loadbalancer.server.port: 5000
      # Registry: Unauthenticated endpoint
      traefik.http.routers.registry-s.entrypoints: https
      traefik.http.routers.registry-s.rule: HostRegexp(`gitlab.${DOMAIN:?You must supply DOMAIN}`) && PathPrefix(`/v2`)
      traefik.http.routers.registry-s.service: registry
      traefik.http.routers.registry-s.tls: "true"
      # SSH: service port
      traefik.tcp.services.ssh.loadbalancer.server.port: 2222
      # SSH: TLS passthrough
      traefik.tcp.routers.ssh.entrypoints: ssh
      traefik.tcp.routers.ssh.rule: HostSNI(`gitlab.${DOMAIN:?You must supply DOMAIN}`)
      traefik.tcp.routers.ssh.service: ssh
      traefik.tcp.routers.ssh.tls.passthrough: "true"

  runner:
    build:
      context: runner
    environment:
      REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
      CI_SERVER_URL: https://gitlab.${DOMAIN:?You must supply DOMAIN}
      RUNNER_EXECUTOR: docker
      DOCKER_PRIVILEGED: "true"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock

  # https://docs.gitlab.com/ee/install/docker.html
  vscode:
    build:
      context: vscode
    command:
    - --auth
    - none
    - --proxy-domain
    - vscode.${DOMAIN:?You must supply DOMAIN}
    - --disable-telemetry
    user: ${USER}
    environment:
      DOCKER_USER: ${USER}
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - vscode_config:/home/coder/.config
    - vscode_project:/home/coder/project
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      traefik.enable: "true"
      # Service port
      traefik.http.services.vscode.loadbalancer.server.port: 8080
      # Redirection to HTTPS
      traefik.http.routers.vscode.entrypoints: http
      traefik.http.routers.vscode.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.vscode.service: vscode
      traefik.http.routers.vscode.middlewares: redirect-to-https
      # Authenticated endpoint
      traefik.http.routers.vscode-s.entrypoints: https
      traefik.http.routers.vscode-s.rule: Host(`vscode.${DOMAIN:?You must supply DOMAIN}`)
      traefik.http.routers.vscode-s.service: vscode
      traefik.http.routers.vscode-s.middlewares: seat-auth
      traefik.http.routers.vscode-s.tls: "true"
