# Default values for sbom-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/ckotzbauer/vulnerability-operator
  tag: ""
  pullPolicy: IfNotPresent

args:
  targets: metrics
  min-severity: low
  git-repository: https://github.com/XXX/XXX
  git-path: dev-cluster/sboms
  verbosity: debug
  cron: "0 0 * * * *"

envVars:
  - name: VULN_GIT_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: "vulnerability-operator"
        key: "accessToken"

ignoreRules: ""
# ignore:
#   # This is the full set of supported rule fields:
#   - vulnerability: CVE-2008-4318
#     fix-state: unknown
#     package:
#       name: libcurl
#       version: 1.5.1
#       type: npm
#       location: "/usr/local/lib/node_modules/**"
#
#   # We can make rules to match just by vulnerability ID:
#   - vulnerability: CVE-2017-41432
#
#   # ...or just by a single package field:
#   - package:
#       type: gem

podAnnotations: {}

resources: {}
#  requests:
#    cpu: 500m
#    memory: 250Gi
#  limits:
#    cpu: 100m
#    memory: 100Mi

securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

servicemonitor:
  enabled: true
  relabelings: {}
  metricRelabelings: {}
  additionalLabels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []